### ISSUE TITLE
AccessDenied with the adapter but not with aws s3

### ISSUE THREAD

**Issue by arjay07** [nicekiwi/lowdb-adapter-aws-s3#5]
Basic usage and it won't write to my bucket..

**Comment by nicekiwi** [comment]
Can you give anymore details?

**Comment by arjay07** [comment]
So `aws-sdk` with S3 puts objects and reads object successfully in my main module. Credentials are correct and everything but when I use this adapter it throws an AccessDenied error. My bucket even has a full access policy

**Comment by nicekiwi** [comment]
That's not ideal. I'll look into it.

**Comment by nicekiwi** [comment]
Confirmed. :(

**Comment by arjay07** [comment]
Is there a temporary fix right now? What could be causing this problem?

**Comment by nicekiwi** [comment]
Not yet, im investigating. there's an ongoing discussion about how unhelpful that error is 😅 https://github.com/aws/aws-sdk-js/issues/3048 it dosnt seem to be related to the ACL issue though.

**Comment by arjay07** [comment]
i found a solution! for some reason using promises were making the AWS return access denied which was weird. However I have removed the use of promises and used [deasync](https://github.com/abbr/deasync). I wrote the read method like so: 
`
    read = () => {
        var readData = this.defaultValue;
        
        deasync(S3_CLIENT.getObject({
            Bucket: this.bucketName,
            Key: this.src
        }, (err, data) => {
            if(err){
                if(err.code == "NoSuchKey"){
                    this.write(this.defaultValue);
                }
            }else console.log("Error", err);
            readData = this.deserialize(data);
        }));
        
        return readData;
    };`

**Comment by nicekiwi** [comment]
Curious, though the same can be achieved with native promises, so I'd prefer to that route instead of using another package.

**Comment by nicekiwi** [comment]
Actually.. @arjay07 show me your options object?

**Comment by nicekiwi** [comment]
If you're not passing any options to the `aws` object, the bucket name will be `lowdb-data`, if that's not your bucket name it will fail every time.

**Comment by arjay07** [comment]
Oh I see! That worked! Thank you so much. So I’ll have to make sure that my AWS object has my actual dB name. Thanks!
